// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjpfdfxbxttvatvrnvfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcGZkZnhieHR0dmF0dnJudmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzgxNTMsImV4cCI6MjA2NTU1NDE1M30.YBWci9jHnHs4udq_yON4aj2uxSUaLgfKgHbW1FzEB64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);